revert pre-commit to check if fixer needs to make any changes. using fixer without dry run in pre-commit will stage changes for a second commit

diff --git a/bin/githook/pre-commit b/bin/githook/pre-commit
--- a/bin/githook/pre-commit
+++ b/bin/githook/pre-commit
@@ -1,12 +1,17 @@
 #!/bin/bash
 
 failed=0;
-root_dir=`dirname $(readlink -f $0)`/../..;
+root_dir=`dirname $(readlink -f $0)`/../../;
 
 for FILENAME in `git diff --name-only --staged`
 do
-  full_path=${root_dir}/${FILENAME};
-  php -n -d 'extension=tokenizer.so;' ${root_dir}/vendor/fabpot/php-cs-fixer/php-cs-fixer fix ${full_path};
+  full_path=${root_dir}${FILENAME};
+  result=`php -n -d 'extension=tokenizer.so;' ${root_dir}/vendor/fabpot/php-cs-fixer/php-cs-fixer fix ${full_path} --dry-run`;
+  if [[ ${result} == *"1)"* ]]
+  then
+    echo ${FILENAME}' failed the php-cs-fixer check';
+    failed=1;
+  fi
 done
 
-exit 0;
+exit ${failed};
